"""Initial migration with numeric fields

Revision ID: 057dd100b3e0
Revises: 
Create Date: 2025-10-18 18:13:29.164568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057dd100b3e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('uber_id', sa.String(length=128), nullable=True),
    sa.Column('bolt_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('bolt_earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bolt_id', sa.String(length=128), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('gross_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expenses_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_income', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cash_collected', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_income', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bolt_earnings')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
