"""add UberEarnings model

Revision ID: 3cbe1f453231
Revises: 057dd100b3e0
Create Date: 2025-10-18 18:58:51.816281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbe1f453231'
down_revision = '057dd100b3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uber_earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uber_id', sa.String(length=128), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('gross_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expenses_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_income', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cash_collected', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_income', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uber_earnings')
    # ### end Alembic commands ###
