"""add roles and api fields to user model

Revision ID: 6053e436dc45
Revises: 19efbc71fea1
Create Date: 2025-09-10 11:29:34.478017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6053e436dc45'
down_revision = '19efbc71fea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('uber_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('bolt_id', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bolt_id')
        batch_op.drop_column('uber_id')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
