"""add WeeklyReport table to db

Revision ID: f668b8d39fee
Revises: df3935b4bf12
Create Date: 2025-11-20 21:35:08.214824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f668b8d39fee'
down_revision = 'df3935b4bf12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_name', sa.String(length=128), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_vat_calculated', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_vat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_carryover', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_actual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expenses_net', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expenses_vat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expenses_vat_deductible', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expenses_deductible', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('settlement_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('contract_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fuel_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_report')
    # ### end Alembic commands ###
